# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-21 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='child',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
