# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-25 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170622_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='party',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='hobbies',
            field=models.ManyToManyField(blank=True, to='portal.Hobby'),
        ),
    ]
