# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20170627_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Student'),
        ),
    ]
