# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-02 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20170628_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.ManyToManyField(related_name='children', to='portal.Student')),
                ('parents', models.ManyToManyField(related_name='parents', to='portal.Student')),
            ],
        ),
    ]
