# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_student_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Prefer not to say')], max_length=1),
        ),
    ]
