# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-22 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_auto_20170822_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='social_link',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
