branch-defaults:
  master:
    environment: doc-mad
global:
  application_name: mad
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.4
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: docsocsf
  repository: null
  sc: git
  workspace_type: Application
